development:
   adapter: postgresql
   host: localhost
   port: 5432
   database: spaceship_development
   username: spaceship
   password: dev
   schema_search_path: public
   encoding: utf8
   pool: 10